name: Swift

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-26

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Print version
        run: swift --version

      - name: Build
        run: swift build --verbose

      - name: Run executable
        run: swift run itunes-library-export --help

      - name: Run tests
        if: matrix.os == 'macos-14'
        run: swift test --verbose
