name: Swift

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-26

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Print version
        run: swift --version

      - name: Build
        run: swift build --verbose

      - name: Run executable
        run: swift run itunes-library-export --help

      - name: Run tests
        if: matrix.os == 'macos-14'
        run: swift test --verbose
